#!/bin/bash

# Copyright 2014 Eduardo Oda
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Written by Oda <oda@member.fsf.org>

set -e
set -u

cd -P `dirname $0`

DIR=`dirname \`pwd\``
PARTITION=`df . | head -2 | tail -1 | cut -d ' ' -f 1`
DEVICE=`echo ${PARTITION} | sed -r "s/[0-9]//g"`

echo -n "The MBR of ${DEVICE} will be overwritten. Press ENTER to continue ou Ctrl+C to cancel... "
read ANS

echo "Ok, first create the lilo.conf file..."
ANS="Y"
if [ -e lilo.conf ]; then
	ANS="N"
	echo -n "Ops! There is already a lilo.conf. Overwrite is? [y/N] "
	read ANS
fi
if [ "${ANS}" = "Y" -o "${ANS}" = "y" ]; then
	cat << ENDOFTEXT >lilo.conf
boot=${DEVICE}
#append=" vt.default_utf8=0"
bitmap = /boot/slack.bmp
bmp-colors = 255,0,255,0,255,0
bmp-table = 60,6,1,16
bmp-timer = 65,27,0,255
prompt
timeout = 100
compact
lba32
change-rules
  reset
vga = 773
image = ${DIR}/slackware64-current/kernels/huge.s/bzImage
  initrd = ${DIR}/slackware64-current/isolinux/initrd.img
  append = "load_ramdisk=1 prompt_ramdisk=0 rw SLACK_KERNEL=huge.s"
  label = "Slackware64"
  read-only
image = ${DIR}/slackware64-14.1/kernels/huge.s/bzImage
  initrd = ${DIR}/slackware64-14.1/isolinux/initrd.img
  append = "load_ramdisk=1 prompt_ramdisk=0 rw SLACK_KERNEL=huge.s"
  label = "Slackware64-141"
  read-only
image = ${DIR}/slackware-current/kernels/huge.s/bzImage
  initrd = ${DIR}/slackware-current/isolinux/initrd.img
  append = "load_ramdisk=1 prompt_ramdisk=0 rw SLACK_KERNEL=huge.s"
  label = "Slackware"
  read-only
image = ${DIR}/slackware-14.1/kernels/huge.s/bzImage
  initrd = ${DIR}/slackware-14.1/isolinux/initrd.img
  append = "load_ramdisk=1 prompt_ramdisk=0 rw SLACK_KERNEL=huge.s"
  label = "Slackware-141"
  read-only
image = ${DIR}/gparted/live-hd/vmlinuz
  initrd = ${DIR}/gparted/live-hd/initrd.img
  vga = 788
  append = "boot=live config union=aufs noswap noprompt ip=frommedia live-media-path=/gparted/live-hd bootfrom=/dev/sdb2 toram=filesystem.squashfs"
  label = "GParted"
  read-only
ENDOFTEXT
fi

echo "Sync discs..."
sync

echo "Running lilo. You may see some warnings. Don't worry."
lilo -C lilo.conf -S /dev/null -m USB.map -b ${DEVICE}
#lilo -C lilo.conf -S /dev/null -b ${DEVICE}

echo "Ok! Do you see any errors? If you don't then we are done!"

